#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx test',
    source=['aybabtu_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target='aybabtu_tests',
    use=['aybabtu', 'gtest'])
