language: bash
matrix:
  include:
    - name: Linux Ubuntu 16 - g++
      os: linux
      dist: xenial
      compiler: gcc
    - name: Linux Ubuntu 18 - g++
      os: linux
      dist: bionic
      compiler: gcc
    - name: Linux Ubuntu 18 - clang
      os: linux
      dist: bionic
      compiler: clang
      env:
        - CXX=clang++
    - name: MacOSX 10.14 - XCode 11
      os: osx
      osx_image: xcode11
      compiler: clang
    - name: Windows - Visual Studio 2017
      os: windows
      env:
        - PYTHONIOENCODING=UTF-8
        - CHOCO_PYTHON="/c/Python27"
      before_install:
        - choco install python2
        - export PATH=$CHOCO_PYTHON:$PATH
        - echo $PATH
      install:
        - python --version
        - echo $PATH
        - which python
        - python waf configure
install:
  - python waf configure
script:
  - python waf build -v --run_tests